
const header=document.querySelector('[data-header]');const toggle=document.querySelector('.nav-toggle');const nav=document.querySelector('#site-nav');
if(header){const onScroll=()=>header.classList.toggle('scrolled',scrollY>12);onScroll();addEventListener('scroll',onScroll,{passive:true})}
if(toggle&&nav){toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open))});nav.addEventListener('click',e=>{if(e.target.matches('a')){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}})}
document.querySelectorAll('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());
const reveals=document.querySelectorAll('.reveal');if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});reveals.forEach(el=>observer.observe(el))}else{reveals.forEach(el=>el.classList.add('visible'))}
const search=document.querySelector('[data-article-search]');const filters=[...document.querySelectorAll('[data-filter]')];const cards=[...document.querySelectorAll('[data-article-grid] .article-card')];const searchStatus=document.querySelector('[data-search-status]');let activeFilter='all';
function filterArticles(){if(!cards.length)return;const term=(search?.value||'').trim().toLowerCase();let visible=0;cards.forEach(card=>{const category=card.dataset.category||'';const matchesFilter=activeFilter==='all'||category===activeFilter;const matchesSearch=!term||(card.dataset.search||'').includes(term);card.hidden=!(matchesFilter&&matchesSearch);if(!card.hidden)visible++});if(searchStatus)searchStatus.textContent=`Showing ${visible} of ${cards.length} NGCYBIT Exchange insights.`}
if(search){search.addEventListener('input',filterArticles);filters.forEach(button=>button.addEventListener('click',()=>{filters.forEach(item=>item.classList.remove('active'));button.classList.add('active');activeFilter=button.dataset.filter;filterArticles()}));filterArticles()}
const copyButton=document.querySelector('[data-copy-address]');if(copyButton){copyButton.addEventListener('click',async()=>{const status=document.querySelector('[data-copy-status]');try{await navigator.clipboard.writeText('20 N E ST, SAN BERNARDINO, CALIFORNIA 92401');status.textContent='Address copied.'}catch{status.textContent='Copy unavailable. Select the address above.'}})}
const form=document.querySelector('[data-contact-form]');if(form){form.addEventListener('submit',event=>{event.preventDefault();const status=form.querySelector('[data-form-status]');if(!form.checkValidity()){form.reportValidity();status.textContent='Please complete every required field.';return}status.textContent='Your inquiry is prepared. This static GitHub Pages demonstration does not transmit form data.';form.reset()})}
